/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tads.cgms.lsm.pratica4.gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'false'", classUnderTest.someLibraryMethod());
    }
}
