/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tads.gcms.lsm.pratica4.ci;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
