/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tads.cgms.lsm.pratica4.gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
   
}

